name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - name: C/C++ Linter
        uses: cpp-linter/cpp-linter-action@v2.6.0
      - name: Run a script
        run: |
          mkdir result
          cl /EHsc main.cpp /link /out:result\sample.exe
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: result/
  send:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir result
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: result
      - name: Send result to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: result/sample.exe
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker build -t sample-container:latest .
          docker run sample-container:latest
          docker exec -it sample-container:latest 100
      - uses: ishworkh/docker-image-artifact-upload@v2.0.1
        with: 
          image: sample-container:latest
