name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a script
        run: |
          mkdir result
          g++ main.cpp -o -m32 result/sample
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: result/
